"""
Plugin SDK — Plugin Health Monitor.

Continuously monitors plugin health:
  - Status checks (healthy, degraded, unhealthy, broken)
  - Resource usage (memory, CPU, execution time)
  - Error rate tracking
  - Crash detection
  - Dependency health
  - Security alerts

Generates automatic alerts when unhealthy plugins are detected.
"""
from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set

logger = logging.getLogger(__name__)


class HealthStatus(str, Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    BROKEN = "broken"
    UNKNOWN = "unknown"


@dataclass
class PluginMetrics:
    """Runtime metrics for a plugin."""
    memory_usage_mb: float = 0.0
    cpu_usage_percent: float = 0.0
    average_execution_time_ms: float = 0.0
    last_execution_time_ms: float = 0.0
    crash_count: int = 0
    error_rate: float = 0.0  # 0-1
    response_time_ms: float = 0.0
    total_executions: int = 0


@dataclass
class HealthAlert:
    """An alert generated by the health monitor."""
    id: str
    plugin_id: str
    severity: str  # "info", "warning", "critical"
    message: str
    timestamp: str
    acknowledged: bool = False
    metric: str = ""
    value: float = 0.0
    threshold: float = 0.0


@dataclass
class PluginHealthSnapshot:
    """Complete health snapshot for a plugin at a point in time."""
    plugin_id: str
    status: HealthStatus = HealthStatus.UNKNOWN
    metrics: PluginMetrics = field(default_factory=PluginMetrics)
    last_check: str = ""
    last_error: Optional[str] = None
    dependencies: List[Dict[str, Any]] = field(default_factory=list)
    alerts: List[HealthAlert] = field(default_factory=list)


@dataclass
class HealthMonitorConfig:
    """Configuration for the health monitor."""
    check_interval: int = 60
    error_rate_threshold: float = 0.1
    crash_threshold: int = 3
    memory_threshold_mb: int = 512
    cpu_threshold_percent: float = 80.0
    execution_time_threshold_ms: int = 300000
    max_consecutive_failures: int = 5
    auto_disable_broken: bool = True


DEFAULT_CONFIG = HealthMonitorConfig()


class PluginHealthMonitor:
    """Continuously monitors all registered plugins."""

    def __init__(self, config: Optional[HealthMonitorConfig] = None):
        self.config = config or DEFAULT_CONFIG
        self._health_states: Dict[str, PluginHealthSnapshot] = {}
        self._check_timers: Dict[str, asyncio.Task] = {}
        self._consecutive_failures: Dict[str, int] = {}
        self._alerts: List[HealthAlert] = []
        self._next_alert_id: int = 1
        self._health_change_handlers: List[Callable] = []
        self._alert_handlers: List[Callable] = []
        logger.info("[HEALTH-MONITOR] Plugin Health Monitor initialized")

    # ── Events ──────────────────────────────────────────────────────────────

    def on_health_change(
        self, callback: Callable
    ) -> Callable:
        """Register a callback for health status changes.
        Returns an unsubscribe function."""
        self._health_change_handlers.append(callback)

        def unsubscribe():
            self._health_change_handlers.remove(callback)

        return unsubscribe

    def on_alert(self, callback: Callable) -> Callable:
        """Register a callback for new alerts.
        Returns an unsubscribe function."""
        self._alert_handlers.append(callback)

        def unsubscribe():
            self._alert_handlers.remove(callback)

        return unsubscribe

    # ── Plugin Registration ─────────────────────────────────────────────────

    def start_monitoring(
        self, plugin_id: str, interval_seconds: Optional[int] = None
    ) -> None:
        """Start monitoring a plugin with periodic health checks."""
        if plugin_id in self._check_timers:
            return

        self._health_states[plugin_id] = PluginHealthSnapshot(
            plugin_id=plugin_id,
            status=HealthStatus.UNKNOWN,
            metrics=PluginMetrics(),
            last_check=datetime.now(timezone.utc).isoformat(),
        )
        self._consecutive_failures[plugin_id] = 0

        interval = (interval_seconds or self.config.check_interval)

        # Start background periodic health check task
        async def _periodic_check():
            try:
                while True:
                    await asyncio.sleep(interval)
                    await self.run_health_check(plugin_id)
            except asyncio.CancelledError:
                pass

        task = asyncio.create_task(_periodic_check())
        self._check_timers[plugin_id] = task

        logger.info(
            f"[HEALTH-MONITOR] Started monitoring plugin '{plugin_id}' "
            f"(interval: {interval}s)"
        )

    def stop_monitoring(self, plugin_id: str) -> None:
        """Stop monitoring a plugin."""
        task = self._check_timers.pop(plugin_id, None)
        if task:
            task.cancel()
        self._health_states.pop(plugin_id, None)
        self._consecutive_failures.pop(plugin_id, None)
        logger.info(f"[HEALTH-MONITOR] Stopped monitoring plugin '{plugin_id}'")

    # ── Health Checks ──────────────────────────────────────────────────────

    async def run_health_check(self, plugin_id: str) -> HealthStatus:
        """Run a health check for a plugin. Performs the check synchronously."""
        state = self._health_states.get(plugin_id)
        if not state:
            return HealthStatus.UNKNOWN

        previous = state.status
        start_time = time.monotonic() * 1000

        try:
            # In production, this would call plugin.on_health_check()
            state.metrics.response_time_ms = time.monotonic() * 1000 - start_time
            state.last_check = datetime.now(timezone.utc).isoformat()

            status = self._evaluate_health(state)
            state.status = status

            self._check_thresholds(plugin_id, state)
            self._consecutive_failures[plugin_id] = 0

            if status != previous:
                self._emit_health_change(plugin_id, status, previous, state)

            if status == HealthStatus.BROKEN or status == HealthStatus.UNHEALTHY:
                cf = self._consecutive_failures.get(plugin_id, 0)
                if cf >= self.config.max_consecutive_failures and self.config.auto_disable_broken:
                    logger.error(
                        f"[HEALTH-MONITOR] Plugin '{plugin_id}' BROKEN "
                        f"({cf} failures) — auto-disable recommended"
                    )

            return status

        except Exception as e:
            err_msg = str(e)
            state.last_error = err_msg
            state.status = HealthStatus.BROKEN
            state.last_check = datetime.now(timezone.utc).isoformat()

            cf = self._consecutive_failures.get(plugin_id, 0) + 1
            self._consecutive_failures[plugin_id] = cf

            self._create_alert(
                plugin_id, "critical",
                f"Health check failed: {err_msg}",
                "error_rate", float(cf), float(self.config.max_consecutive_failures),
            )

            self._emit_health_change(plugin_id, HealthStatus.BROKEN, previous, state)
            return HealthStatus.BROKEN

    # ── Health Evaluation ───────────────────────────────────────────────────

    def _evaluate_health(self, state: PluginHealthSnapshot) -> HealthStatus:
        """Evaluate overall health from metrics."""
        m = state.metrics
        plugin_id = state.plugin_id

        # Broken conditions
        if m.crash_count >= self.config.crash_threshold:
            return HealthStatus.BROKEN
        if self._consecutive_failures.get(plugin_id, 0) >= self.config.max_consecutive_failures:
            return HealthStatus.BROKEN

        # Unhealthy conditions
        if m.error_rate > self.config.error_rate_threshold:
            return HealthStatus.UNHEALTHY
        if m.memory_usage_mb > self.config.memory_threshold_mb:
            return HealthStatus.UNHEALTHY

        # Degraded conditions
        if m.cpu_usage_percent > self.config.cpu_threshold_percent:
            return HealthStatus.DEGRADED
        if m.average_execution_time_ms > self.config.execution_time_threshold_ms:
            return HealthStatus.DEGRADED

        return HealthStatus.HEALTHY

    def _check_thresholds(
        self, plugin_id: str, state: PluginHealthSnapshot
    ) -> None:
        """Check metrics against thresholds and create alerts."""
        m = state.metrics

        if m.memory_usage_mb > self.config.memory_threshold_mb:
            self._create_alert(
                plugin_id, "warning",
                f"High memory usage: {m.memory_usage_mb:.1f}MB "
                f"(threshold: {self.config.memory_threshold_mb}MB)",
                "memory_usage_mb", m.memory_usage_mb,
                float(self.config.memory_threshold_mb),
            )

        if m.cpu_usage_percent > self.config.cpu_threshold_percent:
            self._create_alert(
                plugin_id, "warning",
                f"High CPU usage: {m.cpu_usage_percent:.1f}% "
                f"(threshold: {self.config.cpu_threshold_percent}%)",
                "cpu_usage_percent", m.cpu_usage_percent,
                float(self.config.cpu_threshold_percent),
            )

        if m.crash_count > 0:
            self._create_alert(
                plugin_id, "critical",
                f"Plugin crashed {m.crash_count} time(s)",
                "crash_count", float(m.crash_count), 1.0,
            )

        if m.error_rate > self.config.error_rate_threshold:
            self._create_alert(
                plugin_id, "warning",
                f"High error rate: {m.error_rate * 100:.1f}% "
                f"(threshold: {self.config.error_rate_threshold * 100:.0f}%)",
                "error_rate", m.error_rate,
                float(self.config.error_rate_threshold),
            )

    # ── Metrics Recording ───────────────────────────────────────────────────

    def record_execution(
        self,
        plugin_id: str,
        duration_ms: int,
        success: bool,
        memory_usage_mb: Optional[float] = None,
        cpu_usage_percent: Optional[float] = None,
    ) -> None:
        """Record execution metrics for a plugin."""
        state = self._health_states.get(plugin_id)
        if not state:
            return

        m = state.metrics
        m.total_executions += 1
        m.last_execution_time_ms = float(duration_ms)

        # Rolling average
        m.average_execution_time_ms = (
            (m.average_execution_time_ms * (m.total_executions - 1) + duration_ms)
            / m.total_executions
        )

        if memory_usage_mb is not None:
            m.memory_usage_mb = memory_usage_mb
        if cpu_usage_percent is not None:
            m.cpu_usage_percent = cpu_usage_percent

        if not success:
            m.crash_count += 1
            m.error_rate = min(1.0, m.error_rate + 0.1)
        else:
            m.error_rate = max(0.0, m.error_rate - 0.01)

    def record_crash(self, plugin_id: str, error: str) -> None:
        """Record a crash for a plugin."""
        state = self._health_states.get(plugin_id)
        if not state:
            return

        state.metrics.crash_count += 1
        state.last_error = error

        self._create_alert(
            plugin_id, "critical",
            f"Plugin crashed: {error[:200]}",
            "crash_count", float(state.metrics.crash_count),
            float(self.config.crash_threshold),
        )

        logger.error(f"[HEALTH-MONITOR] Plugin '{plugin_id}' crashed: {error}")

    # ── Alert Management ────────────────────────────────────────────────────

    def _create_alert(
        self,
        plugin_id: str,
        severity: str,
        message: str,
        metric: str,
        value: float,
        threshold: float,
    ) -> HealthAlert:
        """Create a new health alert."""
        alert = HealthAlert(
            id=f"alert-{self._next_alert_id}-{int(time.time())}",
            plugin_id=plugin_id,
            severity=severity,
            message=message,
            timestamp=datetime.now(timezone.utc).isoformat(),
            metric=metric,
            value=value,
            threshold=threshold,
        )
        self._next_alert_id += 1

        self._alerts.append(alert)

        # Keep only last 1000 alerts
        if len(self._alerts) > 1000:
            self._alerts = self._alerts[-1000:]

        # Add to plugin's current alerts
        state = self._health_states.get(plugin_id)
        if state:
            state.alerts.append(alert)
            if len(state.alerts) > 50:
                state.alerts = state.alerts[-50:]

        # Notify handlers (iterate on a copy to avoid mutation during iteration)
        for handler in list(self._alert_handlers):
            try:
                handler(alert)
            except Exception as e:
                logger.error(f"[HEALTH-MONITOR] Alert handler error: {e}")

        logger.warning(f"[HEALTH-MONITOR] Alert [{severity}] {plugin_id}: {message}")
        return alert

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def get_unacknowledged_alerts(self) -> List[HealthAlert]:
        """Get all unacknowledged alerts."""
        return [a for a in self._alerts if not a.acknowledged]

    def get_alerts_for_plugin(self, plugin_id: str) -> List[HealthAlert]:
        """Get alerts for a specific plugin."""
        return [a for a in self._alerts if a.plugin_id == plugin_id]

    # ── Event Emitter ───────────────────────────────────────────────────────

    def _emit_health_change(
        self,
        plugin_id: str,
        status: HealthStatus,
        previous: HealthStatus,
        state: PluginHealthSnapshot,
    ) -> None:
        """Notify health change handlers."""
        event = {
            "plugin_id": plugin_id,
            "status": status.value,
            "previous": previous.value,
            "alerts": [a.__dict__ for a in state.alerts if not a.acknowledged],
        }
        # Notify handlers (iterate on a copy to avoid mutation during iteration)
        for handler in list(self._health_change_handlers):
            try:
                handler(event)
            except Exception as e:
                logger.error(f"[HEALTH-MONITOR] Health change handler error: {e}")

    # ── Queries ─────────────────────────────────────────────────────────────

    def get_health(self, plugin_id: str) -> Optional[PluginHealthSnapshot]:
        """Get health snapshot for a plugin."""
        return self._health_states.get(plugin_id)

    def get_all_health(self) -> List[PluginHealthSnapshot]:
        """Get health snapshots for all monitored plugins."""
        return list(self._health_states.values())

    def get_by_status(self, status: HealthStatus) -> List[PluginHealthSnapshot]:
        """Get plugins by health status."""
        return [s for s in self._health_states.values() if s.status == status]

    def get_stats(self) -> Dict[str, int]:
        """Get health statistics across all plugins."""
        stats = {
            "total": 0, "healthy": 0, "degraded": 0,
            "unhealthy": 0, "broken": 0, "unknown": 0,
            "alerts": len(self._alerts),
            "unacknowledged_alerts": len(self.get_unacknowledged_alerts()),
        }
        for state in self._health_states.values():
            stats["total"] += 1
            if state.status == HealthStatus.HEALTHY:
                stats["healthy"] += 1
            elif state.status == HealthStatus.DEGRADED:
                stats["degraded"] += 1
            elif state.status == HealthStatus.UNHEALTHY:
                stats["unhealthy"] += 1
            elif state.status == HealthStatus.BROKEN:
                stats["broken"] += 1
            else:
                stats["unknown"] += 1
        return stats

    # ── Lifecycle ───────────────────────────────────────────────────────────

    async def shutdown(self) -> None:
        """Stop all monitoring."""
        for task in self._check_timers.values():
            task.cancel()
        self._check_timers.clear()
        self._health_states.clear()
        self._alerts.clear()
        logger.info("[HEALTH-MONITOR] Monitor shut down")


# ── Singleton ───────────────────────────────────────────────────────────────

plugin_health_monitor = PluginHealthMonitor()
